name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.11', '3.13']
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-python@v7.0.0
        with:
          python-version: ${{ matrix.python }}
      - run: python -W error::ResourceWarning -m unittest discover -s tests -v
